export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"

# export PYTHONPATH=$PYTHONPATH:/Users/mitch/bin/PyLibs

# eval "$(/opt/homebrew/bin/brew shellenv)"
